Project Name: Job Portal Database
Database: Oracle SQL
Goal:Manage users,jobs and job applications

--user table creation

create table users(
    user_id Number generated by default as identity primary key,
    username varchar2(100) NOT NULL,
    password varchar2(100) NOT NULL,
    role varchar2(20)check (role in ('admin','user'))
);

--job table creation

create table jobs(
    job_id number generated by default as identity primary key,
    title varchar(100),
    company varchar2(100),
    description varchar2(500),
    approved number default 0
);


create applications table

create table applications(
    application_id number generated by default as identity primary key,
    user_id Number,
    job_id Number,
    application_date Date default sysdate,
    
    constraint fk_user foreign key (user_id)references users(user_id),
    constraint fk_job foreign key (job_id)references jobs(job_id)

);

Insert Sample Data

insert sample data to users:

insert into users(username,password,role)values('admin1','admin123','admin');
insert into users(username,password,role)values('mohana','mohana123','user');
insert into users(username,password,role)values('rahul','rahul123','user');

insert sample data to jobs:

insert into jobs(title,company,description,approved)
values('Python Developer','TCS','flask,sql,apis',1);

insert into jobs(title,company,description,approved)
values('Frontend Developer','Infosys','HTML,CSS,JS',1);

insert into jobs(title,company,description,approved)
values(' Data Analyst','Wipro','Sql,Exel,Power BI',0);


--insert sample data to Applications:

INSERT INTO applications (user_id, job_id)
VALUES (4, 1);
insert into applications(user_id,job_id)
values(3,2);

--view approved jobs:

select *from jobs where approved =1;

--view users & their applications

select u.username, j.title
from applications a
join users u on a.user_id = u.user_id
join jobs j on a.job_id = j.job_id;


--count applications per job

select j.title, count(a.application_id) AS total_applications
from jobs j
left join applications a
on j.job_id = a.job_id
group by j.title;

--users who have not applied any job

select username from users
where user_id not in (select user_id from applications);

--approve jobs

update jobs set approved =1 where job_id = 3;

--view

create view approved_jobs as
select title,company from jobs where approved = 1;

--stored procedure

create or replace procedure apply_job(
    p_user_id number,
    p_job_id number
)as
begin
    insert into applications(user_id,job_id)
    values (p_user_id,p_job_id);
end;

--Trigger(Log Applications)

create or replace trigger job_apply_trigger
after insert on applications
for each row
begin
    DBMS_OUTPUT.PUT_LINE('New job application added');
end;


--Built an Oracle SQL Job Portal database using tables, joins, views, procedures, and triggers.